#DUBBO
dubbox:
  application:
    name: chinogo-web-order
    organization: dubbox
    owner: chinogo
  registry:
    protocol: zookeeper
    address: www.chinotan.cn:2181
  annotation:
    package: cn.chinogo.order.controller
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

server:
  port: 8108

# swagger2
swagger2.package: cn.chinogo.order.controller

# 支付成功回调页面
aliPay:
  returnUrlSuccess: http://localhost:9999/#/order/paysuccess
  returnUrlFailed: http://localhost:9999/#/order/payFailed