#DUBBO
dubbox:
  application:
    name: chinogo-web-upload
    organization: dubbox
    owner: chinogo
  registry:
    protocol: zookeeper
    address: www.chinotan.cn:2181
  annotation:
    package: cn.chinogo.upload.controller
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

server:
  port: 10000

# swagger2
swagger2.package: cn.chinogo.upload.controller

# fastdfs url 查看图片的地址
fastdfs.base.url: http://192.168.217.146/

# fastdfs storage
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.217.155:22122

