#DUBBO
dubbox:
  application:
    name: chinogo-web-search
    organization: dubbox
    owner: chinogo
  registry:
    protocol: zookeeper
    address: www.chinotan.cn:2181
  annotation:
    package: cn.chinogo.search.controller
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

server:
  port: 8102

# swagger2
swagger2.package: cn.chinogo.search.controller

## Search Rows
search_result_rows: 60