#DUBBO
dubbox:
  application:
    name: chinogo-web-base
    organization: dubbox
    owner: chinogo
  registry:
    protocol: zookeeper
    address: www.chinotan.cn:2181
  annotation:
    package: cn.chinogo.base.controller
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

server:
  port: 8333
  
spring.http.multipart.maxFileSize: 10Mb  
spring.http.multipart.maxRequestSize: 100Mb  

# swagger2
swagger2.package: cn.chinogo.base.controller

# Redis
redisKey:
  prefix:
    # 用户登录信息前缀
    user_session: 'USER_SESSION:'
    
# fastdfs url 查看图片的地址
fastdfs.base.url: http://192.168.210.130/

# fastdfs storage
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.210.128:22122
    connect_timeout: 1000000
    network_timeout: 3000000
    charset: UTF-8